from task4 import *
clean_sin=generate_sin_wave(2,(-2,8),1000)
dirty_sin=noisify(clean_sin,0.05**2)
cleaned_sin=mean_filter(dirty_sin,1)
xaxis=np.linspace(-2,8,1000,endpoint=True)
fig, ax = plt.subplots( nrows=1, ncols=1 )
ax.plot(xaxis, clean_sin)
fig.savefig('clean_sin.png')
plt.close(fig) 
fig, ax = plt.subplots( nrows=1, ncols=1 )
ax.plot(xaxis, dirty_sin)
fig.savefig('dirty_sin.png')
plt.close(fig)
fig, ax = plt.subplots( nrows=1, ncols=1 )
ax.plot(xaxis, cleaned_sin)
fig.savefig('cleaned_sin.png')
plt.close(fig) 
