school:
	@echo $@
MPC: school
	@echo $@
BiPC: school
	@echo $@
JEE: MPC
	@echo $@
IIT: JEE
	@echo $@
NIT: JEE
	@echo $@
Hard.Eng: NIT
	@echo $@
Soft.Eng: IIT
	@echo $@
MS: IIT
	@echo $@
Research.Eng: Soft.Eng MS
	@echo $@
NEET: BiPC
	@echo $@
AIIMS: NEET
	@echo $@
CMC: NEET
	@echo $@
Gynic:AIIMS
	@echo $@
ENT: AIIMS
	@echo $@
MD: AIIMS
	@echo $@
Dentist: CMC
	@echo $@
IVF.spec: Gynic MD
	@echo $@
